openapi: 3.0.3
info:
  title: API de cine
  version: 0.0.1
paths:
  /sesiones:
    get:
      summary: Obtiene una lista de sesiones
      description: Este endpoint devuelve una lista con todas las sesiones disponibles y sus detalles.
      parameters:
        - name: fecha
          in: query
          required: false
          description: Fecha para filtrar las sesiones (en formato ISO 8601, por ejemplo, 2025-03-08T14:30:00Z)
          schema:
            type: string
            format: date-time
        - name: formato
          in: query
          required: false
          description: Formato de la sesión (3D, 4D, 2D)
          schema:
            type: string
            enum: [3D, 4D, 2D]
        - name: sala
          in: query
          required: false
          description: Nombre de la sala donde se proyecta la película
          schema:
            type: string
      responses:
        200:
          description: Lista de sesiones disponibles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    fecha:
                      type: string
                      format: date-time
                      example: 2025-03-08T14:30:00Z
                    sala:
                      type: string
                      example: Sala 2
                    pelicula:
                      type: string
                      example: Nueva Película
                    version:
                      type: string
                      example: Versión doblada al castellano
                    formato:
                      type: string
                      enum: [3D, 4D, 2D]
                      example: 2D
                    asientos_disponibles:
                      type: integer
                      example: 100
                    adaptada:
                      type: boolean
                      example: false
                    precio:
                      type: number
                      format: float
                      example: 10.50
                    otros:
                      type: string
                      example: Detalles adicionales de la sesión
        400:
          description: Algún parametro está mal
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Parámetro incorrecto.
    post:
      summary: Crea una nueva sesión
      description: Crea una nueva sesión con los detalles proporcionados en el cuerpo de la solicitud.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fecha:
                  type: string
                  format: date-time
                  example: 2025-03-08T14:30:00Z
                sala:
                  type: string
                  example: Sala 2
                pelicula:
                  type: string
                  example: Nueva Película
                version:
                  type: string
                  example: Versión doblada al castellano
                formato:
                  type: string
                  enum: [3D, 4D, 2D]
                  example: 2D
                asientos_disponibles:
                  type: integer
                  example: 100
                adaptada:
                  type: boolean
                  example: false
                precio:
                  type: number
                  format: float
                  example: 10.50
                otros:
                  type: string
                  example: Detalles adicionales de la sesión
      responses:
        201:
          description: Sesión creada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
        400:
          description: Datos inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Datos de la sesión no válidos

  /sesiones/{id}:
    get:
      summary: Obtiene detalles de una sesión específica
      description: Devuelve la información de una sesión con el ID especificado.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la sesión
          schema:
            type: integer
      responses:
        200:
          description: Detalles de la sesión
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  fecha:
                    type: string
                    format: date-time
                    example: 2025-03-08T14:30:00Z
                  sala:
                    type: string
                    example: Sala 2
        404:
          description: Sesión no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Sesión no encontrada

    put:
      summary: Modifica una sesión
      description: Permite actualizar los detalles de una sesión existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la sesión
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fecha:
                  type: string
                  format: date-time
                  example: 2025-03-08T16:00:00Z
                sala:
                  type: string
                  example: Sala 3
                precio:
                  type: number
                  format: float
                  example: 12.00
      responses:
        200:
          description: Sesión actualizada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Sesión actualizada con éxito
        404:
          description: Sesión no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Sesión no encontrada

    delete:
      summary: Elimina una sesión
      description: Borra una sesión del sistema.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la sesión
          schema:
            type: integer
      responses:
        200:
          description: Sesión eliminada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Sesión eliminada con éxito
        404:
          description: Sesión no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Sesión no encontrada

  /sesiones/{id}/reservar:
    post:
      summary: Comprar una entrada para una sesión
      description: Permite comprar una entrada para una sesión especificada, incluyendo el número de entradas y los asientos a reservar.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la sesión para la que se desea comprar la entrada
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_entradas:
                  type: integer
                  example: 2
                asientos:
                  type: array
                  items:
                    type: string
                    example: A1
                  description: Lista de asientos a reservar
      responses:
        201:
          description: Entrada comprada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Entrada comprada con éxito
                  entrada:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      numero_entradas:
                        type: integer
                        example: 2
                      asientos:
                        type: array
                        items:
                          type: string
                          example: A1
        400:
          description: El JSON no es correcto
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Los datos enviados son incorrectos
        401:
          description: No estamos autorizados
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No estás autorizado para realizar esta acción
        403:
          description: No tenemos permiso
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No tienes permiso para comprar entradas para esta sesión
        404:
          description: ID no válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No se encontró la sesión con el ID especificado

  /peliculas:
    get:
      summary: Listado de películas
      description: Devuelve una lista con las películas disponibles.
      responses:
        200:
          description: Películas disponibles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      example: La Bella y la Bestia
                    duracion:
                      type: integer
                      example: 120
                    genero:
                      type: string
                      example: Fantasía
                    clasificacion:
                      type: string
                      example: PG-13

  /peliculas/{id}:
    put:
      summary: Modifica una película
      description: Actualiza los datos de una película existente.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la película
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: La La Land
                duracion:
                  type: integer
                  example: 128
                genero:
                  type: string
                  example: Musical
                clasificacion:
                  type: string
                  example: PG-13
      responses:
        200:
          description: Película actualizada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Película actualizada con éxito
        404:
          description: Película no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Película no encontrada

    delete:
      summary: Elimina una película
      description: Borra una película del sistema.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la película
          schema:
            type: integer
      responses:
        200:
          description: Película eliminada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Película eliminada con éxito
        404:
          description: Película no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Película no encontrada
  /peliculas/{id}/sesiones:
    get:
      summary: Sesiones de una película concreta
      description: Devuelve una lista de sesiones de una película específica, con la opción de filtrar por los parámetros de la sesión.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la película
          schema:
            type: integer
        - name: fecha
          in: query
          required: false
          description: Fecha para filtrar las sesiones (en formato ISO 8601, por ejemplo, 2025-03-08T14:30:00Z)
          schema:
            type: string
            format: date-time
        - name: formato
          in: query
          required: false
          description: Formato de la sesión (3D, 4D, 2D)
          schema:
            type: string
            enum: [3D, 4D, 2D]
        - name: sala
          in: query
          required: false
          description: Nombre de la sala donde se proyecta la película
          schema:
            type: string
      responses:
        200:
          description: Lista de sesiones disponibles para la película
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    fecha:
                      type: string
                      format: date-time
                      example: 2025-03-08T14:30:00Z
                    sala:
                      type: string
                      example: Sala 2
                    pelicula:
                      type: string
                      example: Nueva Película
                    version:
                      type: string
                      example: Versión doblada al castellano
                    formato:
                      type: string
                      enum: [3D, 4D, 2D]
                      example: 2D
                    asientos_disponibles:
                      type: integer
                      example: 100
                    adaptada:
                      type: boolean
                      example: false
                    precio:
                      type: number
                      format: float
                      example: 10.50
                    otros:
                      type: string
                      example: Detalles adicionales de la sesión
        404:
          description: No se encontraron sesiones para la película especificada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No se encontraron sesiones para la película con el ID especificado
